- id: snyk-terragrunt
  name: Snyk IaC for Terragrunt (plan all env.hcl dirs)
  description: Always run terragrunt plan in every dir containing env.hcl, then scan rendered IaC with Snyk
  entry: hooks/snyk_terragrunt.sh
  language: script
  # Run on every commit regardless of the files changed
  always_run: true
  # We don’t need filenames from pre-commit
  pass_filenames: false
  require_serial: true