- id: snyk-terragrunt-plans
  name: Snyk IaC on Terragrunt plan JSONs (env.hcl dirs)
  description: Always run terragrunt plan in every dir with env.hcl, export tfplan.json, then scan with Snyk --scan=planned-values
  entry: hooks/snyk_terragrunt.sh
  language: script
  always_run: true
  pass_filenames: false
  require_serial: true