- id: snyk-iac
  name: Snyk IaC scan (Terraform/Terragrunt)
  entry: hooks/snyk_iac.sh
  language: script
  files: \.(tf|tfvars|hcl|hcl\.json)$
  pass_filenames: true
  require_serial: true
  args: ['bash', '-c', 'hooks/snyk_iac.sh "$@"', '--']