- id: snyk-terragrunt
  name: Snyk IaC scan for Terragrunt stacks
  entry: hooks/snyk_terragrunt.sh
  language: script
  files: '(^|/)terragrunt\.hcl$'
  pass_filenames: true
  require_serial: true
  args: ['bash', '-c', 'hooks/snyk_terragrunt.sh "$@"', '--']