- id: snyk-terragrunt
  name: Snyk IaC scan for Terragrunt stacks
  description: Run `snyk iac test` against Terraform rendered in .terragrunt-cache for changed Terragrunt stacks
  entry: hooks/snyk_terragrunt.sh
  language: script
  # Trigger only on terragrunt files. If you keep other .hcl files, narrow to (^|/)terragrunt\.hcl$
  files: '(^|/)terragrunt\.hcl$'
  pass_filenames: true
  require_serial: true